dist: bionic
language: python
python:
  - "3.8"
install:
  - sudo apt update
  - sudo apt install -y pkg-config gphoto2 libgphoto2-dev
  - pip install -r requirements_dev.txt
script:
  - make lint
  - make test
#  - python ./docs.py
